### ISSUE TITLE
File is created in wrong place

### ISSUE THREAD

**Issue by jimmyt1988** [davisb10/EasyNetPGP#1]
https://github.com/davisb10/EasyNetPGP/blob/7cbfca92638000e98c6caa9c136ce196ed703374/EasyNetPGP/PgpEncryptorDecryptor.cs#L204

The process tries to create the file where the _pgpLiteralData.FileName is, rather than where it's supposed to: decryptedFilePath

**Comment by davisb10** [comment]
This should be resolved in version 2.0.0 that was just released. Let me know if you still have issues.

**Comment by jimmyt1988** [comment]
@davisb10 - Is it right that the plugin now depends on quite a few system assemblies?

![image](https://user-images.githubusercontent.com/4400555/52949851-63cbc680-3375-11e9-849a-38306b4535c4.png)
![image](https://user-images.githubusercontent.com/4400555/52949870-6d552e80-3375-11e9-9e8a-cffc320c1916.png)
![image](https://user-images.githubusercontent.com/4400555/52949876-71814c00-3375-11e9-8379-4b9f94dd2a97.png)

**Comment by davisb10** [comment]
@jimmyt1988 Yes, from what I can see. Targeting .NET Standard can have this effect on packages.
https://stackoverflow.com/a/47366401
